"""Piezoelectric cantilever example.

Demonstrates modeling of piezoelectric cantilevers using AlN (aluminum nitride)
and PZT (lead zirconate titanate) materials. Piezoelectric cantilevers convert
mechanical strain directly to electrical charge/voltage without requiring an
external bias.

Two sensing modes are compared:
- Voltage mode: Measures voltage across the piezoelectric layer
- Charge mode: Measures charge generated by the piezoelectric layer

The example also demonstrates the Sader hydrodynamic damping model for
calculating Q factor and damped resonant frequency in different fluids.
"""

import addcopyfighandler  # noqa: F401
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("piezod")

from piezod import CantileverPiezoelectric, FluidType, PiezoMaterial

# =============================================================================
# Example 1: AlN piezoelectric cantilever
# =============================================================================

# Create an AlN cantilever for force sensing
c_aln = CantileverPiezoelectric(
    freq_min=1,
    freq_max=1000,
    l_si=500e-6,  # 500 um silicon length
    w_si=50e-6,  # 50 um width
    t_si=5e-6,  # 5 um silicon thickness
    t_pe=500e-9,  # 500 nm AlN layer
    material=PiezoMaterial.ALN,
    r_shunt=1e12,  # High impedance (effectively open)
    fluid=FluidType.AIR,
)

print("=" * 70)
print("Piezoelectric Cantilever Examples")
print("=" * 70)
print()

print("=== Example 1: AlN Piezoelectric Cantilever ===")
print(f"Silicon: {c_aln.l_si * 1e6:.0f} x {c_aln.w_si * 1e6:.0f} x {c_aln.t_si * 1e6:.1f} um")
print(f"AlN thickness: {c_aln.t_pe * 1e9:.0f} nm")
print()
print(f"Stiffness: {c_aln.stiffness:.3f} N/m")
print(f"Resonant frequency (vacuum): {c_aln.resonant_frequency / 1e3:.2f} kHz")
print(f"Effective mass: {c_aln.effective_mass * 1e9:.2f} ng")
print()
print(f"Piezoelectric capacitance: {c_aln.Cpe * 1e12:.2f} pF")
print(f"Piezoelectric resistance: {c_aln.Rpe:.2e} ohm")
print()
print(f"Intrinsic charge sensitivity: {c_aln.q_f_sensitivity_intrinsic * 1e15:.2f} fC/N")
print()

# =============================================================================
# Example 2: Voltage mode vs Charge mode comparison
# =============================================================================

print("=== Example 2: Voltage Mode vs Charge Mode ===")
print(f"{'Parameter':<35} {'Voltage Mode':>15} {'Charge Mode':>15}")
print("-" * 67)

freq_test = np.array([100.0])  # Test at 100 Hz
v_sens = c_aln.v_f_sensitivity(freq_test)[0]
q_sens = c_aln.q_f_sensitivity(freq_test)[0]

print(f"{'Sensitivity @ 100 Hz':<35} {v_sens:>15.2f} V/N {q_sens * 1e15:>12.2f} fC/N")
print(f"{'Force resolution (pN)':<35} {c_aln.Fminv() * 1e12:>15.1f} {c_aln.Fminq() * 1e12:>15.1f}")
print(f"{'Displacement resolution (pm)':<35} {c_aln.Xminv() * 1e12:>15.1f} {c_aln.Xminq() * 1e12:>15.1f}")
print(f"{'Integrated noise':<35} {c_aln.Vn_total() * 1e6:>15.2f} uV {c_aln.Qn_total() * 1e15:>12.2f} fC")
print()

# =============================================================================
# Example 3: AlN vs PZT comparison
# =============================================================================

c_pzt = CantileverPiezoelectric(
    freq_min=1,
    freq_max=1000,
    l_si=500e-6,
    w_si=50e-6,
    t_si=5e-6,
    t_pe=500e-9,
    material=PiezoMaterial.PZT,
    r_shunt=1e12,
    fluid=FluidType.AIR,
)

print("=== Example 3: AlN vs PZT Materials ===")
print(f"{'Parameter':<35} {'AlN':>15} {'PZT':>15}")
print("-" * 67)
print(f"{'d31 coefficient (pC/N)':<35} {c_aln.d31 * 1e12:>15.1f} {c_pzt.d31 * 1e12:>15.1f}")
print(f"{'Relative permittivity':<35} {c_aln.permittivity / 8.854e-12:>15.0f} {c_pzt.permittivity / 8.854e-12:>15.0f}")
print(f"{'Elastic modulus (GPa)':<35} {c_aln.E_pe / 1e9:>15.0f} {c_pzt.E_pe / 1e9:>15.0f}")
print(f"{'Capacitance (pF)':<35} {c_aln.Cpe * 1e12:>15.2f} {c_pzt.Cpe * 1e12:>15.2f}")
q_sens_aln = c_aln.q_f_sensitivity_intrinsic * 1e15
q_sens_pzt = c_pzt.q_f_sensitivity_intrinsic * 1e15
print(f"{'Charge sensitivity (fC/N)':<35} {q_sens_aln:>15.2f} {q_sens_pzt:>15.2f}")
print(f"{'Fmin charge mode (pN)':<35} {c_aln.Fminq() * 1e12:>15.1f} {c_pzt.Fminq() * 1e12:>15.1f}")
print(f"{'Stiffness (N/m)':<35} {c_aln.stiffness:>15.3f} {c_pzt.stiffness:>15.3f}")
print()

# =============================================================================
# Example 4: Fluid damping effects (Sader model)
# =============================================================================

print("=== Example 4: Fluid Damping (Sader Model) ===")
print(f"{'Fluid':<12} {'f_damped (kHz)':>18} {'Q factor':>15}")
print("-" * 47)

for fluid in [FluidType.VACUUM, FluidType.AIR, FluidType.WATER]:
    c_aln.fluid = fluid
    omega_damped, Q = c_aln.omega_damped_and_Q()
    f_damped = omega_damped / (2 * np.pi)
    print(f"{fluid.value:<12} {f_damped / 1e3:>18.2f} {Q:>15.1f}")

# Reset to air
c_aln.fluid = FluidType.AIR
print()

# =============================================================================
# Example 5: Thermomechanical noise limit
# =============================================================================

print("=== Example 5: Fundamental Noise Limits ===")
print(f"Thermomechanical force limit (air): {c_aln.thermomechanical_force_limit() * 1e12:.2f} pN")
print(f"Actual force resolution (voltage): {c_aln.Fminv() * 1e12:.1f} pN")
print(f"Actual force resolution (charge):  {c_aln.Fminq() * 1e12:.1f} pN")
print()

# =============================================================================
# Plot: Sensitivity and noise comparison
# =============================================================================

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

freq = np.logspace(0, 3, 500)

# Plot 1: Voltage sensitivity vs frequency
ax1 = axes[0, 0]
v_sens_aln = c_aln.v_f_sensitivity(freq)
c_pzt.fluid = FluidType.AIR
v_sens_pzt = c_pzt.v_f_sensitivity(freq)
ax1.loglog(freq, v_sens_aln, "b-", label="AlN")
ax1.loglog(freq, v_sens_pzt, "r-", label="PZT")
ax1.set_xlabel("Frequency (Hz)")
ax1.set_ylabel("Voltage Sensitivity (V/N)")
ax1.set_title("Voltage Mode Force Sensitivity")
ax1.legend()

# Plot 2: Voltage noise comparison
ax2 = axes[0, 1]
Vn_aln = c_aln.Vn(freq)
Vn_pzt = c_pzt.Vn(freq)
ax2.loglog(freq, Vn_aln * 1e9, "b-", label="AlN")
ax2.loglog(freq, Vn_pzt * 1e9, "r-", label="PZT")
ax2.set_xlabel("Frequency (Hz)")
ax2.set_ylabel("Voltage Noise (nV/sqrt(Hz))")
ax2.set_title("Voltage Mode Noise")
ax2.legend()

# Plot 3: Force noise density (voltage mode)
ax3 = axes[1, 0]
Sfminv_aln = c_aln.Sfminv(freq)
Sfminv_pzt = c_pzt.Sfminv(freq)
ax3.loglog(freq, Sfminv_aln * 1e12, "b-", label="AlN")
ax3.loglog(freq, Sfminv_pzt * 1e12, "r-", label="PZT")
ax3.set_xlabel("Frequency (Hz)")
ax3.set_ylabel("Force Noise (pN/sqrt(Hz))")
ax3.set_title("Force Noise Density (Voltage Mode)")
ax3.legend()

# Plot 4: Force noise density (charge mode)
ax4 = axes[1, 1]
Sfminq_aln = c_aln.Sfminq(freq)
Sfminq_pzt = c_pzt.Sfminq(freq)
ax4.loglog(freq, Sfminq_aln * 1e12, "b-", label="AlN")
ax4.loglog(freq, Sfminq_pzt * 1e12, "r-", label="PZT")
ax4.set_xlabel("Frequency (Hz)")
ax4.set_ylabel("Force Noise (pN/sqrt(Hz))")
ax4.set_title("Force Noise Density (Charge Mode)")
ax4.legend()

plt.tight_layout()
plt.savefig("piezoelectric_cantilever_comparison.png")
print("Saved comparison plot to: piezoelectric_cantilever_comparison.png")

# =============================================================================
# Plot: Q factor vs aspect ratio
# =============================================================================

fig2, ax5 = plt.subplots(figsize=(8, 5))

# Vary length while keeping width constant
lengths = np.linspace(100e-6, 1000e-6, 20)
Q_air = []
Q_water = []

for L in lengths:
    c_test = CantileverPiezoelectric(
        freq_min=1,
        freq_max=1000,
        l_si=L,
        w_si=50e-6,
        t_si=5e-6,
        t_pe=500e-9,
        material=PiezoMaterial.ALN,
        r_shunt=1e12,
        fluid=FluidType.AIR,
    )
    _, Q = c_test.omega_damped_and_Q()
    Q_air.append(Q)

    c_test.fluid = FluidType.WATER
    _, Q = c_test.omega_damped_and_Q()
    Q_water.append(Q)

ax5.semilogy(lengths * 1e6, Q_air, "b-", linewidth=2, label="Air")
ax5.semilogy(lengths * 1e6, Q_water, "r-", linewidth=2, label="Water")
ax5.set_xlabel("Cantilever Length (um)")
ax5.set_ylabel("Quality Factor Q")
ax5.set_title("Q Factor vs Cantilever Length (w = 50 um)")
ax5.legend()
ax5.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("piezoelectric_Q_vs_length.png", dpi=150)
print("Saved Q factor plot to: piezoelectric_Q_vs_length.png")
